### ISSUE TITLE
Questions about training environment

### ISSUE THREAD

**Issue by nhathoangx007** [whn09/table_structure_recognition#3]
Thanks for your repo. I have some questions about your training environment, in order to reproduce the result.
1. How much RAM needed for training yolov5 with this large dataset?
2. Which GPU(s) did you use?
3. How long did the training last?

I am currently working on the field of table recognition and your repo is very interesting. Thank you very much.

Edit: Mentioned @whn09 for reference.

**Comment by whn09** [comment]
Hi,

I trained the models for about 10 hours/model on AWS ml.p3.2xlarge (1 NVIDIA V100 GPU (16GB GPU Memory), 8 CPU, 64GB RAM).

**Comment by nhathoangx007** [comment]
@whn09
Thanks, may I ask one more question? What is your recommendation about OCR for postprocessing?

**Comment by whn09** [comment]
I think PaddleOCR is suitable for English and Chinese, and Amazon Textract or other SaaS services may be better.
